name: Post Archiver

on:
  schedule:
    - cron:  '00 5 * * *'
  workflow_dispatch:
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip3 install -r requirements.txt
      - name: Run Archiver
        run: python3 main.py
      - name: Publish Archive
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Upload archive"
          add: "."
